sudo: false
language: php

# The nightly builds are a week old. Wait until php 8.0 is stabilized?
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - phpize
  - ./configure
  - make
  - make install
  - echo "extension=ast.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - REPORT_EXIT_STATUS=1 php ./run-tests.php -P -q --show-diff

